#pragma once

#include <cstddef>

// Generated by tools/package_kizz_phoneme_student_firmware.py. Do not edit.
namespace kizz_control_deployment {
inline constexpr float kRawScoreThreshold = -2.16120067f;
inline constexpr float kCollisionBeta = 0.0f;
inline constexpr float kDisplayProbabilityCutoff = 0.70f;
inline constexpr bool kDeploymentQualified = false;
inline constexpr bool kHardwareEvaluationOnly = true;
inline constexpr std::size_t kOutputCount = 20;
inline constexpr char kModelSha256[] = "1753026675313fb0e77d2a93c002c1942e0069d8ce6459437ba8584666f1c140";
inline constexpr char kQualificationSha256[] = "c791c7e0e187d0bbaad615b271f1d3d78ff4ce81a2a2af2aa8991e5f415bb255";
inline constexpr char kArtifactMetadataSha256[] = "66c1766e7887b02675e3620feda8fa44a29586ae572347330ed522ce1be262e7";
inline constexpr char kDistillationMetadataSha256[] = "4b1e7a5a08ddd7dbf51bfd63b658fb2c906e5691889229ff7beed690c21b31b4";
inline constexpr char kDecoderContractSha256[] = "a277b32a2411775d9c2c8a2a7dea0bf6ce26c52ab6f8bafe958ec059fd967d5e";
inline constexpr char kDecoderAlgorithm[] = "forward_sum_ctc";
}  // namespace kizz_control_deployment
