#!/usr/bin/env python3
"""Generate the compact GNU Unifont table used by the Frame renderer."""

from __future__ import annotations

import gzip
import hashlib
from pathlib import Path
import sys
import urllib.request

VERSION = "17.0.04"
URL = (
    f"https://unifoundry.com/pub/unifont/unifont-{VERSION}/font-builds/"
    f"unifont-{VERSION}.hex.gz"
)
SHA256 = "e808096f98ff04294f0d49452cad51964e2930b7be046ac8e1efadc46b2bab0f"

# Match Dial's text ranges and add combining marks, extended Latin, currency,
# arrows, and common symbols encountered in music metadata.
RANGES = (
    (0x0020, 0x007E),
    (0x00A0, 0x024F),
    (0x0300, 0x052F),
    (0x1E00, 0x1EFF),
    (0x2000, 0x206F),
    (0x20A0, 0x20CF),
    (0x2100, 0x214F),
    (0x2190, 0x21FF),
    (0x2600, 0x26FF),
    (0xFFFD, 0xFFFD),
)


def wanted(codepoint: int) -> bool:
    return any(start <= codepoint <= end for start, end in RANGES)


def fetch() -> bytes:
    with urllib.request.urlopen(URL) as response:
        compressed = response.read()
    digest = hashlib.sha256(compressed).hexdigest()
    if digest != SHA256:
        raise RuntimeError(f"Unifont archive SHA-256 mismatch: {digest}")
    return gzip.decompress(compressed)


def generate(source: bytes) -> str:
    glyphs: list[tuple[int, int, bytes]] = []
    for raw_line in source.decode("ascii").splitlines():
        codepoint_hex, bitmap_hex = raw_line.split(":", 1)
        codepoint = int(codepoint_hex, 16)
        if not wanted(codepoint):
            continue
        bitmap = bytes.fromhex(bitmap_hex)
        if len(bitmap) in (16, 32):
            glyphs.append((codepoint, 8 if len(bitmap) == 16 else 16, bitmap))

    offsets: list[int] = []
    packed = bytearray()
    for _, _, bitmap in glyphs:
        offsets.append(len(packed))
        packed.extend(bitmap)

    lines = [
        "// Generated by frame_app/scripts/generate_unifont_subset.py.",
        f"// GNU Unifont {VERSION}; SIL Open Font License 1.1.",
        "// Do not edit by hand.",
        "",
        "static const uint8_t s_unifont_bitmap[] = {",
    ]
    for offset in range(0, len(packed), 16):
        chunk = packed[offset : offset + 16]
        lines.append("    " + ", ".join(f"0x{byte:02X}" for byte in chunk) + ",")
    lines.extend(("};", "", "static const unifont_glyph_t s_unifont_glyphs[] = {"))
    for (codepoint, width, _), offset in zip(glyphs, offsets):
        lines.append(f"    {{0x{codepoint:04X}, {offset}, {width}}},")
    lines.extend(("};", "", f"#define UNIFONT_GLYPH_COUNT {len(glyphs)}", ""))
    return "\n".join(lines)


def main() -> None:
    output = Path(__file__).resolve().parents[1] / "main" / "eink_font_unifont.inc"
    rendered = generate(fetch())
    output.write_text(rendered, encoding="ascii")
    print(f"generated {output} ({len(rendered)} bytes)")


if __name__ == "__main__":
    sys.exit(main())
