// Font manager - provides pre-rendered bitmap fonts for Unicode support
// Two font families:
// 1. Lato (22px) - for artist names, volume labels, status text
// 2. Noto Sans (28px) - for track names, zone names, volume display
// 3. Material Symbols - icon font for UI controls (play, pause, settings, etc.)
//
// Typography matches Roon's design: Lato for metadata, Noto Sans for content
// Source: https://fontsinuse.com/uses/38585/roon-music-player-redesign
//
// Fonts are converted from TTF to LVGL bitmap format at build time using lv_font_conv.
// This eliminates TinyTTF runtime rasterization and its memory pressure issues.

#include "font_manager.h"

#include <esp_log.h>

static const char *TAG = "font_manager";

// External font declarations (generated by lv_font_conv in fonts/*.c)
extern const lv_font_t lato_22;
extern const lv_font_t notosans_28;
extern const lv_font_t material_icons_22;
extern const lv_font_t material_icons_28;
extern const lv_font_t material_icons_44;
extern const lv_font_t material_icons_60;
extern const lv_font_t lucide_battery_22;

static bool s_initialized = false;

bool font_manager_init(void) {
    if (s_initialized) {
        return true;
    }

    ESP_LOGI(TAG, "Initializing font manager (bitmap fonts)...");
    ESP_LOGI(TAG, "  Text fonts: Lato 22px, Noto Sans 28px");
    ESP_LOGI(TAG, "  Icon fonts: Material Symbols at 22/28/44/60px");

    s_initialized = true;
    ESP_LOGI(TAG, "Font manager initialized successfully");
    return true;
}

// Text font getters (Lato for metadata, Noto Sans for content)
const lv_font_t *font_manager_get_small(void) {
    return &lato_22;
}

const lv_font_t *font_manager_get_normal(void) {
    return &notosans_28;
}

const lv_font_t *font_manager_get_large(void) {
    return &notosans_28;  // Large font uses same 28px size
}

// Icon font getters (Material Symbols for UI controls)
const lv_font_t *font_manager_get_icon_small(void) {
    return &material_icons_22;
}

const lv_font_t *font_manager_get_icon_normal(void) {
    return &material_icons_44;  // Increased from 28px to match 60px buttons
}

const lv_font_t *font_manager_get_icon_large(void) {
    return &material_icons_60;  // Increased from 48px to match 80px play button
}

// Lucide battery font getter (horizontal battery icons)
const lv_font_t *font_manager_get_lucide_battery(void) {
    return &lucide_battery_22;
}

bool font_manager_has_unicode(void) {
    return true;  // Bitmap fonts always available
}

bool font_manager_has_icons(void) {
    return true;  // Bitmap fonts always available
}
