// Font manager - provides pre-rendered bitmap fonts for Unicode support
// Two font families at three sizes each:
// 1. Lato (22/25/28px) - clean sans-serif for metadata
// 2. Noto Sans (22/25/28px) - humanist sans-serif for content
// 3. Material Icons - icon font for UI controls (play, pause, settings, etc.)
//
// Typography matches Roon's design: Lato for metadata, Noto Sans for content
// Source: https://fontsinuse.com/uses/38585/roon-music-player-redesign
//
// Fonts are converted from TTF to LVGL bitmap format at build time using lv_font_conv.
// This eliminates TinyTTF runtime rasterization and its memory pressure issues.

#include "font_manager.h"

#include <esp_log.h>

static const char *TAG = "font_manager";

// External font declarations (generated by lv_font_conv in fonts/*.c)
// Lato family at all sizes
extern const lv_font_t lato_22;
extern const lv_font_t lato_25;
extern const lv_font_t lato_28;

// Noto Sans family at all sizes
extern const lv_font_t notosans_22;
extern const lv_font_t notosans_25;
extern const lv_font_t notosans_28;

// Material Icons at all text sizes + button sizes
extern const lv_font_t material_icons_22;
extern const lv_font_t material_icons_25;
extern const lv_font_t material_icons_28;
extern const lv_font_t material_icons_44;
extern const lv_font_t material_icons_60;

// Lucide battery icons
extern const lv_font_t lucide_battery_22;

static bool s_initialized = false;

bool font_manager_init(void) {
    if (s_initialized) {
        return true;
    }

    ESP_LOGI(TAG, "Initializing font manager (bitmap fonts)...");
    ESP_LOGI(TAG, "  Text fonts: Lato 22/25/28px, Noto Sans 22/25/28px");
    ESP_LOGI(TAG, "  Icon fonts: Material Icons at 22/25/28/44/60px");

    s_initialized = true;
    ESP_LOGI(TAG, "Font manager initialized successfully");
    return true;
}

// Get font by family and size - the primary API for display_config
const lv_font_t *font_manager_get_font(font_family_t family, font_size_t size) {
    if (family == FONT_LATO) {
        switch (size) {
            case FONT_SMALL:  return &lato_22;
            case FONT_MEDIUM: return &lato_25;
            case FONT_LARGE:  return &lato_28;
            default:          return &lato_22;
        }
    } else {  // FONT_NOTOSANS
        switch (size) {
            case FONT_SMALL:  return &notosans_22;
            case FONT_MEDIUM: return &notosans_25;
            case FONT_LARGE:  return &notosans_28;
            default:          return &notosans_28;
        }
    }
}

// Legacy text font getters (for backward compatibility)
const lv_font_t *font_manager_get_small(void) {
    return &lato_22;
}

const lv_font_t *font_manager_get_normal(void) {
    return &notosans_28;
}

const lv_font_t *font_manager_get_large(void) {
    return &notosans_28;
}

// Icon font getters (Material Symbols for UI controls)
const lv_font_t *font_manager_get_icon_small(void) {
    return &material_icons_22;
}

const lv_font_t *font_manager_get_icon_normal(void) {
    return &material_icons_44;  // Increased from 28px to match 60px buttons
}

const lv_font_t *font_manager_get_icon_large(void) {
    return &material_icons_60;  // Increased from 48px to match 80px play button
}

// Lucide battery font getter (horizontal battery icons)
const lv_font_t *font_manager_get_lucide_battery(void) {
    return &lucide_battery_22;
}

bool font_manager_has_unicode(void) {
    return true;  // Bitmap fonts always available
}

bool font_manager_has_icons(void) {
    return true;  // Bitmap fonts always available
}
