// Font manager - provides pre-rendered bitmap fonts for Unicode support
// Two font families:
// 1. Charis SIL - text font for music metadata (artist, track, album)
// 2. Material Symbols - icon font for UI controls (play, pause, settings, etc.)
//
// Fonts are converted from TTF to LVGL bitmap format at build time using lv_font_conv.
// This eliminates TinyTTF runtime rasterization and its memory pressure issues.

#include "font_manager.h"

#include <esp_log.h>

static const char *TAG = "font_manager";

// External font declarations (generated by lv_font_conv in fonts/*.c)
extern const lv_font_t charis_22;
extern const lv_font_t charis_28;
extern const lv_font_t charis_40;
extern const lv_font_t material_icons_22;
extern const lv_font_t material_icons_28;
extern const lv_font_t material_icons_48;

static bool s_initialized = false;

bool font_manager_init(void) {
    if (s_initialized) {
        return true;
    }

    ESP_LOGI(TAG, "Initializing font manager (bitmap fonts)...");
    ESP_LOGI(TAG, "  Text fonts: Charis SIL at 22/28/40px");
    ESP_LOGI(TAG, "  Icon fonts: Material Symbols at 22/28/48px");

    s_initialized = true;
    ESP_LOGI(TAG, "Font manager initialized successfully");
    return true;
}

// Text font getters (Charis SIL for music metadata)
const lv_font_t *font_manager_get_small(void) {
    return &charis_22;
}

const lv_font_t *font_manager_get_normal(void) {
    return &charis_28;
}

const lv_font_t *font_manager_get_large(void) {
    return &charis_40;
}

// Icon font getters (Material Symbols for UI controls)
const lv_font_t *font_manager_get_icon_small(void) {
    return &material_icons_22;
}

const lv_font_t *font_manager_get_icon_normal(void) {
    return &material_icons_28;
}

const lv_font_t *font_manager_get_icon_large(void) {
    return &material_icons_48;
}

bool font_manager_has_unicode(void) {
    return true;  // Bitmap fonts always available
}

bool font_manager_has_icons(void) {
    return true;  // Bitmap fonts always available
}
